name: Building
on: [push]
    
jobs:
  building: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Runing Tests
        run: poetry run pytest --junitxml=jest-junit.xml
      - name: Reporting
        uses: dorny/test-reporter@v1
        if: success()||failure()
        with: 
          name: Tests
          path: jest-junit.xml
          reporter: jest-junit

      - run: poetry build
      
      - name: Publishing
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/dist/* 
        
      

    